### PR TITLE
Log API Refactor

### LINKED ISSUE #19: WithFunc opens bug possibilities
> Regarding the WithFunc, it was added just for more flexibility should a field value depends on context or anything else.

YAGNI. Can you give a specific example of a problem it solves? I can give an example of a problem it introduces: you've now got a way to get into an infinite loop without really realising it.

```go
fields.WithFunc("foo", func(ctx context.Context) interface{} {
    return util.getValueOfFoo(ctx)
}).Onto(ctx)

// somewhere else, some utility package etc
func getValueOfFoo(ctx context.Context) string {
    log.From(ctx).Info("getting value of foo") // infinite recursion here
    return "bar"
}
```

_Originally posted by @jamesrom in https://github.com/anz-bank/pkg/issues/18#issuecomment-581704464_

### PR DESCRIPTION
**Pull request by nofun97**
Fixes #19 

Removed `WithFunc` and changed `WithCtxRef` to `WithContextRef` for clearer name.

### CODE REVIEW

**Comment by jamesrom** [comment]
I'm happy to approve this, but what are your thoughts on WithCtxKey or WithContextKey? We're not passing a reference, and the [context package calls it 'key'](https://golang.org/pkg/context/#WithValue).

**Comment by anzboi** [comment]
I second that, I think i prefer context key. Objections?

**Comment by anzdaddy** [comment]
`WithContextKey` sgtm

**Comment by nofun97** [comment]
changed to `WithContextKey`

**Pull request merged**
